service: sloth-alarm-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev  # Set a default stage value
  environment:
    STRIPE_SECRET_KEY: "sk_test_placeholder"
    FIREBASE_PROJECT_ID: "sloth-dc40d"
    FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC8lxmFKkI5NhMS\nFUO15k7/DFCID5ra6+yNoR/7l2c8Ix2lrY/Eah4sd/9I9B7oAacJ4v713QQA7gYt\ns7gBmK8LZRvxMsZ6I5e1qG6+dmCdZ5jA7BqzUuhlMKIRFO2RFKiR6HxwFOdkLeKm\n+lgiQUbxRj3KrydpqMDXkTDlooJOD7TLqLohFjEpG1+5i7sVSl5QW35fysg8w7rU\nDJLkBKefmlFFS1lGYcxCj2BArUK7ioJUl58/1KVzUdOuTXBrncFv6uagL8XeXz/w\n31Wd38IUXHAF+/gutbbNOWt/IcAVCvZgTzUVkSh9AZyv/JMWxG5+sSzMA0eUpV7e\npbbyXuq5AgMBAAECggEAOdoAMiFsfzBfWUS8qKglw4d7jMF8t3t37Vpn/T3MpV4A\nUjqTx6Tl7K5C2ZZJhNI884N2wuUxvTdHHe3rnFHCILS7hZoV2JHikA9DKZoWuTJ2\nYXgMGMZuE9x/Ws4YslCsBVZUFe3TrZ+Fz8MsFhYANTNe8TYZ2QezYG1hmo/neRpA\njqPM2+zrWx3TJk0Ys1PO6KnKX5we7hHxC7J5sZWFGsvxJ6CObSKqGRYjPaxI14As\nqc1LXmQ9cbhmp2diLrvJNwYj6TfYImSSZmLzGtQhQVN03pUP7K6j8t825yNyK7UK\nvk5brh8HU4c77Hezk7sj1TFPs1uZGCc44rjVvortoQKBgQD3nJ23QIPf0RuHk2Mm\niusQKzZ+bhT55jrcECVLQ5zmoGkDWITXeT3OpFshwZYXg/32q/izD/mcHWZn42/0\n20IK2PtYomZv/LZT0W/HFrH0QUJKOBpy6eA1ujhHLW72jBBi1Emf8oh6WV+2VYD3\nL7mwN2uTWz1LtnHUpFCf/GnYBwKBgQDC+qBO+lJ0SOhVmcc0eLD6C5DxkAknjGm1\nibDP+qwgI8Atlin1C8bkGkdxR/wXGbAlqU8Xo3u9KaIr7BmQ4PaomPs7fA7LNSIw\nVpTSgPl+F7PklM8Z4BpCM3X25+1YklxkPIyJDyJ8ZNkEw/lrEBytkUQcYuCD6zyX\n2o1rAvz3PwKBgBQu4fQ0AAvYYaQVcXmMzUhOHW0E0BTmnVmev0t5QWrTHHw3VOyz\nZ0RWxU7lFrTn/2WB8w21eaUuCFDjixasYJ+9vA8nfa4XLU17vt69jNfaEes204EW\naz415ax3mZnjJNrJbw7omBNRAao9IfwEGeCxQ8WJJF/tiS3KDwBbdM01AoGAe4CV\nGnGk2NN1lwMZEzt/nmLFJL2/jrV6H+tfe92kOZdrm3SKjxUunj2nEzItk9RJpxFf\nb/G151P/zSJ37zUQCCset8cU99JoHYY6LjxTzHLnF9rKc/FnsJc4GXU++eN7cmKI\nAij8Bx8597LKwe4qvCZPpktbOzQ95VIiUa5K3bECgYA3EkXiL2/IQQqwRuEzLCcM\nnrCR9BQLkgPEugOdsyKEc+UeWy9lW77SY2AtI5E4lJ8Mlohffk7rdi3ndmJw6KxT\nSNIAv97vjMTlsrs5tlTRiaDXGTGRoI+o4W5d5RqTec6be9wA4ZuMyH1FK9HThB8O\nMJXPhsLiRO6+Jse8ipBEew==\n-----END PRIVATE KEY-----"
    FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-27do9@sloth-dc40d.iam.gserviceaccount.com"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:*:table/sloth-alarm-app-dev-alarms"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/sloth-alarm-app-dev-users"

functions:
  createAlarm:
    handler: functions/alarms.create
    events:
      - http:
          path: /alarms
          method: post
          cors: true

  getAlarms:
    handler: functions/alarms.list
    events:
      - http:
          path: /alarms
          method: get
          cors: true

  setupIntent:
    handler: functions/payments.createSetupIntent
    events:
      - http:
          path: /setup-intent
          method: post
          cors: true

  savePaymentMethod:
    handler: functions/payments.savePaymentMethod
    events:
      - http:
          path: /save-payment-method
          method: post
          cors: true

  getPaymentMethod:
    handler: functions/payments.getPaymentMethod
    events:
      - http:
          path: /payment-method
          method: get
          cors: true

  checkLocation:
    handler: functions/alarms.checkLocation
    events:
      - http:
          path: /check-location
          method: post
          cors: true

  processPayments:
    handler: functions/payments.processPayments
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    AlarmsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sloth-alarm-app-dev-alarms
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sloth-alarm-app-dev-users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
